#!/bin/bash
#SBATCH --nodes 1
#SBATCH --cpus-per-task 5
#SBATCH --time 03:00:00
#SBATCH --job-name jupyter-notebook
#SBATCH -o /home/mho1/scratch/jupyter_log/jupyter-notebook-%J.log
#SBATCH -e /home/mho1/scratch/jupyter_log/jupyter-notebook-%J.log

# get tunneling info

port=8888
node=$(hostname -s)
user=$(whoami)


# run jupyter notebook
jupyter-notebook --no-browser --port=${port} --ip=${node}



